### ISSUE TITLE
SyntaxError in cli.py

### ISSUE THREAD

**Issue by svmunster** [mara/bingads-performance-downloader#19]
Thanks for all the hard work you put into this.
I'm getting an SyntaxError when running **download-bingsads-performance-data**:

```
Traceback (most recent call last):
  File "/home/sven/.local/bin/download-bingsads-performance-data", line 5, in <module>
    from bingads_downloader.cli import download_data
  File "/home/sven/.local/lib/python3.5/site-packages/bingads_downloader/cli.py", line 15
    help=f'{config_function.__doc__}. Default: "{config_function()}"')(function)
                                                                    ^
SyntaxError: invalid syntax
```

Tried some basic things, but no result. Any suggestion what is going wrong?

**Comment by martin-loetzsch** [comment]
What version of Python are you using?

**Comment by svmunster** [comment]
Fixed this one, it indeed had to do with the python version. Running from a venv solved it.
